[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Remove the redirect as it's not needed for Next.js
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200 