# netlify.toml
[build]
  base = "/"
  publish = "out"
  command = "./netlify-build.sh"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_USE_YARN = "false"
  # Add placeholder values for required environment variables
  NEXT_PUBLIC_SUPABASE_URL = "https://placeholder-supabase-url.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "placeholder-anon-key"
  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY = "placeholder-google-maps-key"

# Remove Next.js plugin since we're using static export
# [[plugins]]
#   package = "@netlify/plugin-nextjs"

# Enable HTTP/2 and HTTP/3
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Cache control for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.googletagmanager.com *.google-analytics.com; style-src 'self' 'unsafe-inline' fonts.googleapis.com; img-src 'self' data: *.cdninstagram.com via.placeholder.com *.google-analytics.com https://*; font-src 'self' fonts.gstatic.com fonts.googleapis.com; connect-src 'self' *.google-analytics.com *.analytics.google.com *.googletagmanager.com; frame-src 'self'"

# Cache static assets for a year
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/optimized/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for static assets - ensure these are served correctly
[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200

[[redirects]]
  from = "/optimized/*"
  to = "/optimized/:splat"
  status = 200

# Handle static HTML files for routes
[[redirects]]
  from = "/blog"
  to = "/blog.html"
  status = 200

[[redirects]]
  from = "/book"
  to = "/book.html"
  status = 200

[[redirects]]
  from = "/brands"
  to = "/brands.html"
  status = 200

[[redirects]]
  from = "/careers"
  to = "/careers.html"
  status = 200

[[redirects]]
  from = "/locations"
  to = "/locations.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/services"
  to = "/services.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/terms.html"
  status = 200

# Fallback redirect for SPA - only apply to routes that don't match files
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
