# netlify.toml
[build]
  base = "/"
  publish = "out"
  command = "./netlify-build.sh"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_USE_YARN = "false"
  # Add placeholder values for required environment variables
  NEXT_PUBLIC_SUPABASE_URL = "https://placeholder-supabase-url.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "placeholder-anon-key"
  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY = "placeholder-google-maps-key"

[[plugins]]
  package = "@netlify/plugin-nextjs"
