# Netlify configuration for Next.js project
[build]
  command = "npm run netlify-build"
  publish = ".next"
  ignore = "git diff --quiet HEAD^ HEAD -- ."

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect all requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 