# netlify.toml
[build]
  base = "/"
  publish = "out"
  command = "./netlify-build.sh"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_USE_YARN = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"
